-- Adiciona a coluna 'preco_venda' à tabela 'adicionais'.
-- Esta coluna armazenará o preço de venda para cada item adicional, permitindo que seja nulo.
-- O tipo 'numeric' é usado para garantir a precisão em cálculos financeiros.
-- Execute este script no SQL Editor do seu projeto Supabase para aplicar a alteração.

ALTER TABLE public.adicionais
ADD COLUMN IF NOT EXISTS preco_venda numeric;

-- =================================================================
-- SCRIPT DE MIGRAÇÃO PARA FUNCIONALIDADE DE INSUMOS ESPECIAIS
-- Execute este bloco de código no seu SQL Editor do Supabase.
-- =================================================================

-- 1. Cria a tabela 'insumos_especiais'
-- Armazena as categorias de insumos, como "Couro" ou "Tecido".
CREATE TABLE IF NOT EXISTS public.insumos_especiais (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nome text NOT NULL
);

-- Habilita Row Level Security (RLS)
ALTER TABLE public.insumos_especiais ENABLE ROW LEVEL SECURITY;

-- Cria políticas de acesso para garantir que os usuários só acessem seus próprios dados.
DROP POLICY IF EXISTS "Enable access for authenticated users" ON public.insumos_especiais;
CREATE POLICY "Enable access for authenticated users" ON public.insumos_especiais
    FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');

-- 2. Cria a tabela 'insumos_especiais_opcoes'
-- Associa as categorias de insumos especiais aos insumos reais.
CREATE TABLE IF NOT EXISTS public.insumos_especiais_opcoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    insumo_especial_id bigint NOT NULL,
    insumo_id bigint NOT NULL,
    CONSTRAINT insumos_especiais_opcoes_insumo_especial_id_fkey FOREIGN KEY (insumo_especial_id) REFERENCES public.insumos_especiais(id) ON DELETE CASCADE,
    CONSTRAINT insumos_especiais_opcoes_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES public.insumos(id) ON DELETE CASCADE
);

-- Habilita RLS
ALTER TABLE public.insumos_especiais_opcoes ENABLE ROW LEVEL SECURITY;

-- Cria políticas de acesso
DROP POLICY IF EXISTS "Enable access for authenticated users" ON public.insumos_especiais_opcoes;
CREATE POLICY "Enable access for authenticated users" ON public.insumos_especiais_opcoes
    FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');


-- 3. Altera a tabela 'fichas_tecnicas'
-- Adiciona suporte para insumos especiais nas fichas técnicas.
ALTER TABLE public.fichas_tecnicas ADD COLUMN IF NOT EXISTS insumo_especial_id bigint;

-- Adiciona a chave estrangeira (foreign key)
ALTER TABLE public.fichas_tecnicas DROP CONSTRAINT IF EXISTS fichas_tecnicas_insumo_especial_id_fkey;
ALTER TABLE public.fichas_tecnicas ADD CONSTRAINT fichas_tecnicas_insumo_especial_id_fkey 
    FOREIGN KEY (insumo_especial_id) REFERENCES public.insumos_especiais(id) ON DELETE SET NULL;

-- Torna a coluna 'insumo_id' nula, pois um item pode ser ou comum ou especial.
ALTER TABLE public.fichas_tecnicas ALTER COLUMN insumo_id DROP NOT NULL;

-- Garante que um item não pode ser um insumo comum E um especial ao mesmo tempo.
ALTER TABLE public.fichas_tecnicas DROP CONSTRAINT IF EXISTS chk_insumo_type;
ALTER TABLE public.fichas_tecnicas ADD CONSTRAINT chk_insumo_type 
    CHECK ((insumo_id IS NOT NULL AND insumo_especial_id IS NULL) OR (insumo_id IS NULL AND insumo_especial_id IS NOT NULL));

-- =================================================================
-- SCRIPT DE MIGRAÇÃO PARA QUANTIDADES POR TAMANHO
-- Adiciona colunas para quantidade de adulto e infantil em insumos especiais.
-- Execute este bloco de código no seu SQL Editor do Supabase.
-- =================================================================

-- Adiciona as novas colunas para quantidades específicas de tamanho
ALTER TABLE public.fichas_tecnicas ADD COLUMN IF NOT EXISTS quantidade_adulto numeric;
ALTER TABLE public.fichas_tecnicas ADD COLUMN IF NOT EXISTS quantidade_infantil numeric;

-- Permite que a coluna 'quantidade' original seja nula
-- Isso é necessário porque a quantidade pode ser definida pelas novas colunas
ALTER TABLE public.fichas_tecnicas ALTER COLUMN quantidade DROP NOT NULL;

-- Adiciona uma restrição para garantir a integridade dos dados de quantidade
-- Um item deve ter ou uma quantidade geral, ou ambas as quantidades de adulto e infantil
ALTER TABLE public.fichas_tecnicas DROP CONSTRAINT IF EXISTS chk_quantidade_options;
ALTER TABLE public.fichas_tecnicas ADD CONSTRAINT chk_quantidade_options 
    CHECK ((quantidade IS NOT NULL AND quantidade_adulto IS NULL AND quantidade_infantil IS NULL) OR (quantidade IS NULL AND quantidade_adulto IS NOT NULL AND quantidade_infantil IS NOT NULL));

-- =================================================================
-- POLÍTICAS DE ACESSO ANÔNIMO PARA O QR CODE
-- Permite que operadores leiam o estoque e insiram consumo sem login
-- =================================================================

-- Insumos
ALTER TABLE public.insumos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.insumos;
CREATE POLICY "Enable read access for all users" ON public.insumos FOR SELECT USING (true);

-- Compras
ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.compras;
CREATE POLICY "Enable read access for all users" ON public.compras FOR SELECT USING (true);

-- Consumo Estoque
ALTER TABLE public.consumo_estoque ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.consumo_estoque;
CREATE POLICY "Enable read access for all users" ON public.consumo_estoque FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.consumo_estoque;
CREATE POLICY "Enable insert access for all users" ON public.consumo_estoque FOR INSERT WITH CHECK (true);

-- Funcionarios
ALTER TABLE public.funcionarios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.funcionarios;
CREATE POLICY "Enable read access for all users" ON public.funcionarios FOR SELECT USING (true);

-- =================================================================
-- FUNCTION TO UPDATE FICHA TECNICA QUANTITIES
-- Bypasses client-side schema cache issues by using RPC.
-- =================================================================

CREATE OR REPLACE FUNCTION public.update_ficha_tecnica_quantities(
    p_id bigint,
    p_quantidade numeric DEFAULT NULL,
    p_quantidade_adulto numeric DEFAULT NULL,
    p_quantidade_infantil numeric DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public.fichas_tecnicas
    SET
        quantidade = p_quantidade,
        quantidade_adulto = p_quantidade_adulto,
        quantidade_infantil = p_quantidade_infantil
    WHERE id = p_id;
END;
$$;

-- =================================================================
-- SCRIPT DE MIGRAÇÃO PARA CONTROLE DE COMPRAS E ESTOQUE
-- =================================================================

CREATE TABLE IF NOT EXISTS public.compras (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    data_compra date NOT NULL,
    fornecedor text NOT NULL,
    insumo_id bigint NOT NULL,
    quantidade numeric NOT NULL,
    preco_unitario numeric NOT NULL,
    valor_total numeric NOT NULL,
    CONSTRAINT compras_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES public.insumos(id) ON DELETE CASCADE
);

ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable access for authenticated users" ON public.compras;
CREATE POLICY "Enable access for authenticated users" ON public.compras
    FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS public.funcionarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nome text NOT NULL,
    codigo_acesso text NOT NULL UNIQUE,
    setor text
);

-- Adiciona a coluna setor caso a tabela já exista
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS setor text;

ALTER TABLE public.funcionarios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable access for authenticated users" ON public.funcionarios;
CREATE POLICY "Enable access for authenticated users" ON public.funcionarios
    FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS public.consumo_estoque (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    data_consumo date NOT NULL,
    insumo_id bigint NOT NULL,
    quantidade numeric NOT NULL,
    motivo text,
    responsavel text,
    funcionario_id bigint,
    CONSTRAINT consumo_estoque_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES public.insumos(id) ON DELETE CASCADE,
    CONSTRAINT consumo_estoque_funcionario_id_fkey FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id) ON DELETE SET NULL
);

ALTER TABLE public.consumo_estoque ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable access for authenticated users" ON public.consumo_estoque;
CREATE POLICY "Enable access for authenticated users" ON public.consumo_estoque
    FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');